name: GitHub Metrics
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # daily
permissions:
  contents: write
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: himanshu60
          filename: github-metrics.svg
          template: classic
          base: header, activity
          config_timezone: Asia/Kolkata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
